// Automatically generated by scripts/build-samples.js. Do not edit directly.
window.MERMAID_SAMPLES = {
  "groups": [
    {
      "id": "diagram-types",
      "name": "Standard Diagram Types",
      "description": "Demonstration templates representing different types of diagrams supported by Mermaid.js."
    },
    {
      "id": "infrastructure",
      "name": "Infrastructure & Systems",
      "description": "Real-world engineering sequence and system diagrams representing homelab flows."
    },
    {
      "id": "project-management",
      "name": "Project Management & Mapping",
      "description": "Templates for timeline planning, tasks management, and system scoping."
    }
  ],
  "samples": [
    {
      "id": "flowchart-basics",
      "group_id": "diagram-types",
      "name": "Flowchart Basics",
      "description": "A basic flowchart demonstrating decisions, conditions, redirects, and custom node styling.",
      "code": "flowchart TD\n    A[Start] --> B{Is SSO Enabled?}\n    B -- Yes --> C[Redirect to Authentik]\n    B -- No --> D[Load Mock Session]\n    C --> E[Callback to App Portal]\n    D --> E\n    E --> F[Render Service Grid]"
    },
    {
      "id": "class-diagram",
      "group_id": "diagram-types",
      "name": "Class Diagram",
      "description": "Object-oriented software design template representing user and application classes.",
      "code": "classDiagram\n    class User {\n        +String username\n        +String email\n        +List groups\n        +isAdmin() Boolean\n    }\n    class Application {\n        +String id\n        +String name\n        +String url\n        +String auth_level\n        +isAccessibleFor(User u) Boolean\n    }\n    User \"1\" --> \"*\" Application : has access to"
    },
    {
      "id": "er-diagram",
      "group_id": "diagram-types",
      "name": "Entity Relationship Diagram",
      "description": "Database design modeling showing user-to-group cardinalities and attributes.",
      "code": "erDiagram\n    USER ||--o{ GROUP : belongs_to\n    USER {\n        string username\n        string email\n    }\n    GROUP {\n        string name\n        string permissions\n    }"
    },
    {
      "id": "state-diagram",
      "group_id": "diagram-types",
      "name": "State Diagram",
      "description": "Finite state machine detailing states and transitions of a deployment pipeline.",
      "code": "stateDiagram-v2\n    [*] --> Idle\n    Idle --> Building : Git Push Trigger\n    Building --> Testing : Compile Success\n    Building --> Failed : Compile Error\n    Testing --> Deploying : Tests Pass\n    Testing --> Failed : Test Failure\n    Deploying --> Active : Health Check OK\n    Deploying --> Failed : Deployment Timeout\n    Failed --> Idle : Acknowledge & Fix\n    Active --> [*] : Terminated"
    },
    {
      "id": "git-graph",
      "group_id": "diagram-types",
      "name": "Git Graph",
      "description": "Visual representation of git branch commits, merges, and tagging structures.",
      "code": "gitGraph\n    commit id: \"Initial Commit\"\n    commit id: \"Setup Ansible Playbooks\"\n    branch feature/sso\n    checkout feature/sso\n    commit id: \"Add NPM Forward Auth config\"\n    commit id: \"Bind Authentik Proxy Providers\"\n    checkout main\n    merge feature/sso tag: \"v1.1.0\"\n    commit id: \"Document architecture\""
    },
    {
      "id": "sequence-sso",
      "group_id": "infrastructure",
      "name": "SSO Forward Auth Flow",
      "description": "Comprehensive sequence diagram of Nginx Proxy Manager and Authentik SSO Forward Auth middleware.",
      "code": "sequenceDiagram\n    actor User as User Browser\n    participant Proxy as Nginx Proxy Manager\n    participant Portal as Homelab Portal (FastAPI)\n    participant Auth as Authentik (192.168.20.202)\n\n    User->>Proxy: GET https://portal.mapleleafhome.net/\n    Proxy->>Auth: Validate Session (Forward Auth)\n    alt Session is invalid / not logged in\n        Auth-->>Proxy: Unauthorized (Redirect to auth.mapleleafhome.net)\n        Proxy-->>User: HTTP 302 Redirect to Authentik Login\n        User->>Auth: Authenticate Credentials\n        Auth-->>User: Set session cookies & Redirect to portal\n    end\n    Auth-->>Proxy: Session Valid (Headers: X-Authentik-*)\n    Proxy->>Portal: Forward Request with Session Cookies\n    Portal->>Auth: GET /api/v3/core/applications/ (Forwarding User Cookies)\n    Auth-->>Portal: List of Authorized Applications for user context\n    Portal-->>User: Render Portal page with filtered applications grid"
    },
    {
      "id": "network-topology",
      "group_id": "infrastructure",
      "name": "Homelab Network Topology",
      "description": "Detailed multi-VLAN layout diagram of Proxmox VE hosts and reverse-proxied guests.",
      "code": "flowchart TB\n    subgraph WAN[\"External Network\"]\n        Client[\"Client / User Browser\"]\n    end\n\n    subgraph Proxmox[\"Dayton Proxmox VE (192.168.20.0/24)\"]\n        Router[\"Nginx Proxy Manager\\n(Edge Router - .201)\"]\n        Portal[\"Homelab Portal\\n(Web UI - .204)\"]\n        Auth[\"Authentik SSO\\n(Auth Provider - .202)\"]\n    end\n\n    subgraph Polaris[\"Polaris VLAN (192.168.120.0/24)\"]\n        AdguardPolaris[\"AdGuard Polaris\\n(DNS Resolver - .214)\"]\n    end\n\n    Client -->|HTTPS:443| Router\n    Router -->|Forward Auth| Auth\n    Router -->|Reverse Proxy| Portal\n    Portal -->|Local Resolution| AdguardPolaris"
    },
    {
      "id": "gantt-chart",
      "group_id": "project-management",
      "name": "Gantt Timeline Chart",
      "description": "Project management timeline scheduling tasks, sections, milestones, and active items.",
      "code": "gantt\n    title Homelab Phase 2 Migration Plan\n    dateFormat  YYYY-MM-DD\n    section Infrastructure Planning\n    Define VLAN & Subnet Map     :active, 2026-08-01, 5d\n    Review SSO Access Levels     : 2026-08-06, 3d\n    section Application Deployments\n    Deploy Netstats Dashboard    : 2026-08-09, 4d\n    Deploy Speedtest Telemetry   : 2026-08-11, 3d\n    section Verification & Cutover\n    User Acceptance Testing      : 2026-08-14, 4d\n    Production DNS Cutover       : 2026-08-18, 1d"
    },
    {
      "id": "mindmap",
      "group_id": "project-management",
      "name": "Architecture Mindmap",
      "description": "Hierarchical mindmap brainstorming homelab resource groups and architecture.",
      "code": "mindmap\n  root((Homelab Hub))\n    Virtualization\n      Proxmox VE\n        LXC Containers\n        KVM VMs\n    Identity SSO\n      Authentik\n        Proxy Provider\n        OIDC Provider\n        Active Directory\n    Networking\n      Nginx Proxy Manager\n      Tailscale VPN\n      AdGuard Home\n    Storage\n      NFS Share\n      ZFS Pool"
    }
  ]
};
