const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const catalogPath = path.join(rootDir, 'samples', 'catalog.json');
const outputPath = path.join(rootDir, 'html', 'samples.js');

function buildSamples() {
  console.log('📦 Compiling Mermaid Diagram Samples Library...');

  if (!fs.existsSync(catalogPath)) {
    console.error(`Error: Catalog file not found at ${catalogPath}`);
    process.exit(1);
  }

  try {
    const catalogRaw = fs.readFileSync(catalogPath, 'utf8');
    const catalog = JSON.parse(catalogRaw);

    const compiledSamples = [];

    for (const sample of catalog.samples) {
      const filePath = path.join(rootDir, 'samples', sample.file);
      console.log(`  - Reading diagram: ${sample.name} (${sample.file})...`);

      if (!fs.existsSync(filePath)) {
        console.error(`  Warning: File ${filePath} not found. Skipping.`);
        continue;
      }

      const code = fs.readFileSync(filePath, 'utf8').trim();
      
      // Build sample object with code contents embedded, discarding the filename reference
      const compiledSample = {
        id: sample.id,
        group_id: sample.group_id,
        name: sample.name,
        description: sample.description,
        code: code
      };

      compiledSamples.push(compiledSample);
    }

    const outputData = {
      groups: catalog.groups,
      samples: compiledSamples
    };

    const outputContent = `// Automatically generated by scripts/build-samples.js. Do not edit directly.
window.MERMAID_SAMPLES = ${JSON.stringify(outputData, null, 2)};
`;

    fs.writeFileSync(outputPath, outputContent, 'utf8');
    console.log(`✅ Success! Compiled samples library saved to: ${outputPath}`);

  } catch (error) {
    console.error('❌ Compilation failed:', error);
    process.exit(1);
  }
}

buildSamples();
